remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true

github:
  is_project_page: false

title: Programación
description: Apuntes de programación del CFGS de Desarrollo de Aplicaciones Multiplataforma.

show_downloads: true
